from datetime import datetime
from flask import Flask, request, send_file
import os

# LOCALHOST = return f'http://127.0.0.1:5000'

CUR_DIR = os.path.dirname(os.path.abspath(__file__))

app = Flask(__name__)

@app.route("/download_dict", methods=['GET'])
def download_dict():
    date = datetime.now().strftime("%d/%m/%Y")
    time = datetime.now().strftime("%H:%M:%S")
    message = f"Message generated by the server in date {date} at {time}."
    return {'message': message}


@app.route("/upload_dict", methods=['POST'])
def upload_dict():
    req = request.get_json()
    text = req['text']
    message = f"Your message '{text}' was rd by the server and returned."
    return {'message': message}


@app.route("/download_file", methods=['GET'])
def download_file():
    file_path = os.path.join(CUR_DIR, "res/download_from_server.txt")
    dt = datetime.now().strftime("%d%m%Y-%H%M%S")
    file_name = f"{dt} File from Server"
    return send_file(file_path, as_attachment=True, download_name=file_name) 


@app.route("/upload_file", methods=['POST'])
def upload_file():
    pass


@app.route("/download_dict_file", methods=['GET'])
def download_dict_file():
    pass


@app.route("/upload_dict_file", methods=['POST'])
def upload_dict_file():
    pass


if __name__ == "__main__":
    app.run(debug=True)
