# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\i.stiaccini\Desktop\playground\APIsFileTransfer\client\gui\ui/api_file_transfer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(509, 312)
        MainWindow.setMinimumSize(QtCore.QSize(509, 312))
        MainWindow.setMaximumSize(QtCore.QSize(509, 312))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 491, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.f_btn_dwn = QtWidgets.QPushButton(self.groupBox_2)
        self.f_btn_dwn.setObjectName("f_btn_dwn")
        self.verticalLayout_2.addWidget(self.f_btn_dwn)
        self.f_btn_up = QtWidgets.QPushButton(self.groupBox_2)
        self.f_btn_up.setObjectName("f_btn_up")
        self.verticalLayout_2.addWidget(self.f_btn_up)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.d_btn_dwn = QtWidgets.QPushButton(self.groupBox)
        self.d_btn_dwn.setObjectName("d_btn_dwn")
        self.verticalLayout.addWidget(self.d_btn_dwn)
        self.d_btn_up = QtWidgets.QPushButton(self.groupBox)
        self.d_btn_up.setObjectName("d_btn_up")
        self.verticalLayout.addWidget(self.d_btn_up)
        self.d_txt = QtWidgets.QPlainTextEdit(self.groupBox)
        self.d_txt.setObjectName("d_txt")
        self.verticalLayout.addWidget(self.d_txt)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.df_btn_dwn = QtWidgets.QPushButton(self.groupBox_3)
        self.df_btn_dwn.setObjectName("df_btn_dwn")
        self.verticalLayout_3.addWidget(self.df_btn_dwn)
        self.df_btn_up = QtWidgets.QPushButton(self.groupBox_3)
        self.df_btn_up.setObjectName("df_btn_up")
        self.verticalLayout_3.addWidget(self.df_btn_up)
        self.df_text = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.df_text.setObjectName("df_text")
        self.verticalLayout_3.addWidget(self.df_text)
        self.gridLayout.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.log_txt = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.log_txt.setObjectName("log_txt")
        self.verticalLayout_4.addWidget(self.log_txt)
        self.gridLayout.addWidget(self.groupBox_4, 1, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 509, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "API File Transfer"))
        self.groupBox_2.setTitle(_translate("MainWindow", "File"))
        self.f_btn_dwn.setText(_translate("MainWindow", "Download"))
        self.f_btn_up.setText(_translate("MainWindow", "Upload"))
        self.groupBox.setTitle(_translate("MainWindow", "Dictionary"))
        self.d_btn_dwn.setText(_translate("MainWindow", "Download"))
        self.d_btn_up.setText(_translate("MainWindow", "Upload"))
        self.d_txt.setPlainText(_translate("MainWindow", "Message to server."))
        self.groupBox_3.setTitle(_translate("MainWindow", "Dict+File"))
        self.df_btn_dwn.setText(_translate("MainWindow", "Download"))
        self.df_btn_up.setText(_translate("MainWindow", "Upload"))
        self.df_text.setPlainText(_translate("MainWindow", "Message to server."))
        self.groupBox_4.setTitle(_translate("MainWindow", "Client Logs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
